# Generated by Django 3.1.4 on 2021-03-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kidney_Feature_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rts_id', models.CharField(blank=True, max_length=25, null=True)),
                ('target_name', models.CharField(blank=True, max_length=25, null=True)),
                ('probe_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('negative', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.category', verbose_name='category of data')),
            ],
            options={
                'verbose_name': 'kidney feature annotation',
                'verbose_name_plural': 'kidney feature annotations',
                'ordering': ['probe_id'],
            },
        ),
    ]
