# Generated by Django 3.1.4 on 2021-03-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidney_sample_annotations',
            name='slug',
            field=models.SlugField(default='tobeupdated', max_length=250),
            preserve_default=False,
        ),
    ]
