# Generated by Django 3.1.4 on 2021-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_kidney_feature_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidney_feature_annotation',
            name='probe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
